[package]
name = "jayrah-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
crossterm = "0.28"
jayrah-config = { path = "../jayrah-config" }
jayrah-jira = { path = "../jayrah-jira" }
ratatui = "0.29"
webbrowser = "1.0"
